library(testthat)
library(mockery)

describe("Test Multiple Functions at depth=2",{
  it("can stub a single function at default depth (1)", {
    print("can stub a single function at default depth (1)")
    source("multiFuncD2.R")
    mD1 <- mock(TRUE)
    stub(Depth0.myFunction,'Depth1.myFunction',mD1)
    Depth0.myFunction()
    expect_called(mD1,1)
  })
  it("can stub a single function at depth=1", {
    print("can stub a single function at depth=1")
    source("multiFuncD2.R")
    mD1 <- mock(TRUE)
    stub(Depth0.myFunction,'Depth1.myFunction',mD1,depth=1)
    Depth0.myFunction()
    expect_called(mD1,1)
  })
  it("can stub a single function at depth=2", {
    print("can stub a single function at depth=2")
    source("multiFuncD2.R")
    mD2A <- mock(TRUE)
    stub(Depth0.myFunction,'Depth2.myFunctionA',mD2A,depth=2)
    Depth0.myFunction()
    expect_called(mD2A,1)
  })
  it("can stub multiple functions at depth=2", {
    print("can stub multiple functions at depth=2")
    source("multiFuncD2.R")
    mD2A <- mock(TRUE)
    mD2B <- mock(TRUE)
    stub(Depth0.myFunction,'Depth2.myFunctionA',mD2A,depth=2)
    stub(Depth0.myFunction,'Depth2.myFunctionB',mD2B,depth=2)
    Depth0.myFunction()
    expect_called(mD2A,1)
    expect_called(mD2B,1)
  })
})
