library(testthat)
library(mockery)

describe("Test Multiple Functions at depth=3",{
  it("can stub a single function at default depth (1)", {
    print("can stub a single function at default depth (1)")
    source("multiFuncD3.R")
    mD1 <- mock(TRUE)
    stub(Depth0.myFunction,'Depth1.myFunction',mD1)
    Depth0.myFunction()
    expect_called(mD1,1)
  })
  it("can stub a single function at depth=1", {
    print("can stub a single function at depth=1")
    source("multiFuncD3.R")
    mD1 <- mock(TRUE)
    stub(Depth0.myFunction,'Depth1.myFunction',mD1,depth=1)
    Depth0.myFunction()
    expect_called(mD1,1)
  })
  it("can stub a single function at depth=2", {
    print("can stub a single function at depth=2")
    source("multiFuncD3.R")
    mD2A <- mock(TRUE)
    stub(Depth0.myFunction,'Depth2.myFunction',mD2A,depth=2)
    Depth0.myFunction()
    expect_called(mD2A,1)
  })
  it("can stub a single function at depth=3", {
    print("can stub a single function at depth=3")
    source("multiFuncD3.R")
    mD3A <- mock(TRUE)
    stub(Depth0.myFunction,'Depth3.myFunctionA',mD3A,depth=3)
    Depth0.myFunction()
    expect_called(mD3A,1)
  })
  it("can stub multiple functions at depth=3", {
    print("can stub multiple functions at depth=3")
    source("multiFuncD3.R")
    mD3A <- mock(TRUE)
    mD3B <- mock(TRUE)
    stub(Depth0.myFunction,'Depth3.myFunctionA',mD3A,depth=3)
    stub(Depth0.myFunction,'Depth3.myFunctionB',mD3B,depth=3)
    Depth0.myFunction()
    expect_called(mD3A,1)
    expect_called(mD3B,1)
  })
})
